using Fabulous.MyMeetings.Modules.Meetings.Application.MeetingGroupProposals.GetMeetingGroupProposal;

namespace Fabulous.MyMeetings.Modules.Meetings.Application.MeetingGroupProposals.GetMemberMeetingGroupProposals;

public class GetMemberMeetingGroupProposalsQuery:Query<IEnumerable<MeetingGroupProposalDto>>;