CREATE TABLE [Users].[QRTZ_TRIGGERS] (
  [SCHED_NAME] nvarchar(120) NOT NULL,
  [TRIGGER_NAME] nvarchar(150) NOT NULL,
  [TRIGGER_GROUP] nvarchar(150) NOT NULL,
  [JOB_NAME] nvarchar(150) NOT NULL,
  [JOB_GROUP] nvarchar(150) NOT NULL,
  [DESCRIPTION] nvarchar(250) NULL,
  [NEXT_FIRE_TIME] bigint NULL,
  [PREV_FIRE_TIME] bigint NULL,
  [PRIORITY] int NULL,
  [TRIGGER_STATE] nvarchar(16) NOT NULL,
  [TRIGGER_TYPE] nvarchar(8) NOT NULL,
  [START_TIME] bigint NOT NULL,
  [END_TIME] bigint NULL,
  [CALENDAR_NAME] nvarchar(200) NULL,
  [MISFIRE_INSTR] int NULL,
  [JOB_DATA] varbinary(max) NULL,
  CONSTRAINT [PK_Users_QRTZ_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
    [SCHED_NAME],
    [TRIGGER_NAME],
    [TRIGGER_GROUP]
  ),
  CONSTRAINT [FK_Users_QRTZ_TRIGGERS_QRTZ_JOB_DETAILS] FOREIGN KEY
  (
    [SCHED_NAME],
    [JOB_NAME],
    [JOB_GROUP]
  ) REFERENCES [Users].[QRTZ_JOB_DETAILS] (
    [SCHED_NAME],
    [JOB_NAME],
    [JOB_GROUP]
  )
);
GO

CREATE INDEX [IDX_Users_QRTZ_T_G_J]                 ON [Users].[QRTZ_TRIGGERS](SCHED_NAME, JOB_GROUP, JOB_NAME);
GO
CREATE INDEX [IDX_Users_QRTZ_T_C]                   ON [Users].[QRTZ_TRIGGERS](SCHED_NAME, CALENDAR_NAME);
GO
CREATE INDEX [IDX_Users_QRTZ_T_N_G_STATE]           ON [Users].[QRTZ_TRIGGERS](SCHED_NAME, TRIGGER_GROUP, TRIGGER_STATE);
GO
CREATE INDEX [IDX_Users_QRTZ_T_STATE]               ON [Users].[QRTZ_TRIGGERS](SCHED_NAME, TRIGGER_STATE);
GO
CREATE INDEX [IDX_Users_QRTZ_T_N_STATE]             ON [Users].[QRTZ_TRIGGERS](SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, TRIGGER_STATE);
GO
CREATE INDEX [IDX_Users_QRTZ_T_NEXT_FIRE_TIME]      ON [Users].[QRTZ_TRIGGERS](SCHED_NAME, NEXT_FIRE_TIME);
GO
CREATE INDEX [IDX_Users_QRTZ_T_NFT_ST]              ON [Users].[QRTZ_TRIGGERS](SCHED_NAME, TRIGGER_STATE, NEXT_FIRE_TIME);
GO
CREATE INDEX [IDX_Users_QRTZ_T_NFT_ST_MISFIRE]      ON [Users].[QRTZ_TRIGGERS](SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_STATE);
GO
CREATE INDEX [IDX_Users_QRTZ_T_NFT_ST_MISFIRE_GRP]  ON [Users].[QRTZ_TRIGGERS](SCHED_NAME, MISFIRE_INSTR, NEXT_FIRE_TIME, TRIGGER_GROUP, TRIGGER_STATE);
GO