
CREATE TABLE [Users].[QRTZ_SIMPROP_TRIGGERS] (
  [SCHED_NAME] nvarchar(120) NOT NULL,
  [TRIGGER_NAME] nvarchar(150) NOT NULL,
  [TRIGGER_GROUP] nvarchar(150) NOT NULL,
  [STR_PROP_1] nvarchar(512) NULL,
  [STR_PROP_2] nvarchar(512) NULL,
  [STR_PROP_3] nvarchar(512) NULL,
  [INT_PROP_1] int NULL,
  [INT_PROP_2] int NULL,
  [LONG_PROP_1] bigint NULL,
  [LONG_PROP_2] bigint NULL,
  [DEC_PROP_1] numeric(13,4) NULL,
  [DEC_PROP_2] numeric(13,4) NULL,
  [BOOL_PROP_1] bit NULL,
  [BOOL_PROP_2] bit NULL,
  [TIME_ZONE_ID] nvarchar(80) NULL,
  CONSTRAINT [PK_Users_QRTZ_SIMPROP_TRIGGERS] PRIMARY KEY  CLUSTERED
  (
	[SCHED_NAME],
	[TRIGGER_NAME],
	[TRIGGER_GROUP]
  ),
  CONSTRAINT [FK_Users_QRTZ_SIMPROP_TRIGGERS_QRTZ_TRIGGERS] FOREIGN KEY
  (
	[SCHED_NAME],
	[TRIGGER_NAME],
	[TRIGGER_GROUP]
  ) REFERENCES [Users].[QRTZ_TRIGGERS] (
	[SCHED_NAME],
	[TRIGGER_NAME],
	[TRIGGER_GROUP]
  ) ON DELETE CASCADE
);
GO