CREATE TABLE [Users].[Users]
(
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY CLUSTERED,
    [Email] NVARCHAR (255) NOT NULL,
    [Password] NVARCHAR(255) NOT NULL,
    [IsActive] BIT NOT NULL,
    [FirstName] NVARCHAR(50) NOT NULL,
    [LastName] NVARCHAR(50) NOT NULL,
    [Name] NVARCHAR (255) NOT NULL
)
GO